### ISSUE TITLE
After tapping '=' and user taps another number, clear last calculation

### ISSUE THREAD

**Issue by fvalela1** [fvalela1/AndroidTutorial_Winter2018#3]
If you tap '=' and then tap another number, it won't do anything. Must clear last calculation and allow it to start from blank

**Comment by fvalela1** [comment]
After fiddling around, it's just the view that isn't refreshing. 

If you were to go: 
> 4-3 = 1
> you tap 55555
> it will still show 1.0 at the top and 1 at the bottom.
> you press any operator, like '-'
> 55555 -

**Comment by jacobrs** [comment]
Will test with calculator logic
